
USE learepladsDB;

DROP ROLE IF EXISTS Operator;
DROP USER IF EXISTS Novice;

CREATE ROLE Operator;

GRANT EXECUTE, SELECT ON * TO Operator;

CREATE USER Novice IDENTIFIED BY 'MysqlNovice' DEFAULT ROLE Operator;
ALTER USER Novice PASSWORD EXPIRE NEVER;